/* Generated By:JavaCC: Do not edit this line. CommentParserConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CommentParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int REMAIN_TOKEN = 3;
  /** RegularExpression Id. */
  int QUOTE = 4;
  /** RegularExpression Id. */
  int QUOTED_STRING = 5;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE = 6;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE_STRING = 7;
  /** RegularExpression Id. */
  int ANY = 8;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WITHINCOMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"/*\"",
    "<token of kind 2>",
    "<REMAIN_TOKEN>",
    "\"\\\'\"",
    "<QUOTED_STRING>",
    "\"\\\"\"",
    "<DOUBLE_QUOTE_STRING>",
    "<ANY>",
    "\"*/\"",
    "<token of kind 10>",
  };

}
